### ISSUE TITLE
The compilation has terminated with an unexpected error.

### ISSUE THREAD

**Issue by Zamiell** [theseanl/tscc#210]
```
Zamiell@computer js % npx tscc --debug
TSCC: TypeError: Cannot read property 'map' of undefined
    at transformBundle (/Users/Zamiell/Repositories/hanabi-live/public/js/node_modules/@tscc/tscc/node_modules/typescript/lib/typescript.js:70027:53)
    at transformSourceFileOrBundle (/Users/Zamiell/Repositories/hanabi-live/public/js/node_modules/@tscc/tscc/node_modules/typescript/lib/typescript.js:70022:24)
    at transformation (/Users/Zamiell/Repositories/hanabi-live/public/js/node_modules/@tscc/tscc/node_modules/typescript/lib/typescript.js:85827:24)
    at transformRoot (/Users/Zamiell/Repositories/hanabi-live/public/js/node_modules/@tscc/tscc/node_modules/typescript/lib/typescript.js:85847:82)
    at Object.map (/Users/Zamiell/Repositories/hanabi-live/public/js/node_modules/@tscc/tscc/node_modules/typescript/lib/typescript.js:507:29)
    at Object.transformNodes (/Users/Zamiell/Repositories/hanabi-live/public/js/node_modules/@tscc/tscc/node_modules/typescript/lib/typescript.js:85834:30)
    at emitJsFileOrBundle (/Users/Zamiell/Repositories/hanabi-live/public/js/node_modules/@tscc/tscc/node_modules/typescript/lib/typescript.js:86340:32)
    at emitSourceFileOrBundle (/Users/Zamiell/Repositories/hanabi-live/public/js/node_modules/@tscc/tscc/node_modules/typescript/lib/typescript.js:86293:13)
    at forEachEmittedFile (/Users/Zamiell/Repositories/hanabi-live/public/js/node_modules/@tscc/tscc/node_modules/typescript/lib/typescript.js:86073:34)
    at Object.emitFiles (/Users/Zamiell/Repositories/hanabi-live/public/js/node_modules/@tscc/tscc/node_modules/typescript/lib/typescript.js:86274:9)
```

tsconfig:
```
{
    "compilerOptions": {
        "downlevelIteration": true,
        "importHelpers": true, // Not necessary since TSCC forces it, but oh well
        "module": "commonjs", // Not necessary since TSCC forces it, but oh well
    },

    "include": [
        "./src/**/*.ts",
    ],
}
```

tscc.spec.json:
```
{
    "modules": {
        "out": "src/main.ts"
    }
}
```

1) The --debug command seems to do nothing.
2) The error message is pretty unhelpful

Any tips?

**Comment by mattrenaud** [comment]
@Zamiell Had the same issue when i ran it through `npx`. Installing it globally fixed it: `npm i -g @tscc/tscc` then running `tscc` instead.

**Comment by theseanl** [comment]
If `npx` fixes it, it could be due to typescript version mismatch. Also, as I recall the `transformBundle` code path should not be taken for projects fed to tsickle. If there are some files that are not 'modules', i.e. without `export` or `import` statements, try making those into modules. In any case a minimal reproduction case would be helpful.
