### ISSUE TITLE
Fails with TypeScript incremental flag

### ISSUE THREAD

**Issue by pbadenski** [theseanl/tscc#294]
`tsconfig.json` contains `incremental: true`:
```
...
  "compilerOptions": {
    "incremental": true,
...
```

Error:

````
TSCC: The compilation has terminated with an unexpected error.
TSCC: Error: Unrecognized file extension /Users/pbadenski/workspace/app/tsconfig.tsbuildinfo.
    at writeFile (/Users/pbadenski/workspace/app/node_modules/@tscc/tscc/dist/tscc.js:227:23)
    at Object.writeFileImpl [as writeFile] (/Users/pbadenski/workspace/app/node_modules/@tscc/tscc/node_modules/tsickle/src/tsickle.js:112:13)
    at Object.writeFile (/Users/pbadenski/workspace/app/node_modules/@tscc/tscc/node_modules/typescript/lib/typescript.js:16612:14)
    at emitBuildInfo (/Users/pbadenski/workspace/app/node_modules/@tscc/tscc/node_modules/typescript/lib/typescript.js:94678:16)
    at emitSourceFileOrBundle (/Users/pbadenski/workspace/app/node_modules/@tscc/tscc/node_modules/typescript/lib/typescript.js:94644:13)
    at forEachEmittedFile (/Users/pbadenski/workspace/app/node_modules/@tscc/tscc/node_modules/typescript/lib/typescript.js:94403:28)
    at Object.emitFiles (/Users/pbadenski/workspace/app/node_modules/@tscc/tscc/node_modules/typescript/lib/typescript.js:94623:9)
    at emitWorker (/Users/pbadenski/workspace/app/node_modules/@tscc/tscc/node_modules/typescript/lib/typescript.js:100827:33)
    at /Users/pbadenski/workspace/app/node_modules/@tscc/tscc/node_modules/typescript/lib/typescript.js:100806:66
    at runWithCancellationToken (/Users/pbadenski/workspace/app/node_modules/@tscc/tscc/node_modules/typescript/lib/typescript.js:100902:24)

**Comment by theseanl** [comment]
Incremental compilation is not supported. As I understand, it will compile modified files only, but tscc needs a full compilation output currently. If there is some sort of incremental compilation support in closure compiler, it would make sense to implement incremental compilation in tscc, but as far as I know there is no such thing.

Currently, apart from the error you've reported, the presence of `incremental` flag in tsconfig does not make any difference. We always call `ts.createCompilerHost` but incremental compilation requires `ts.createIncrementalCompilationHost` in place of that. That's why it looks like the compilation work if it was not for the error. I think what we can do here is to override `incremental` flag to be false and reporting it to the user.

**Comment by pbadenski** [comment]
Thanks, I understand now, this is really useful context!

**Comment by aminya** [comment]
I faced this issue when `declaration` was enabled. So setting these two fixes the error temporarily:
```json
    "declaration": false,
    "incremental": false,
```

**Comment by theseanl** [comment]
With `@tscc/tscc 0.5.2`, it will silently ignore the `declaration` key of tsconfig and no longer fail the builds.
